python run_kuairand.py --model_name ple --task click --device cuda:1 --seed 2022
python run_kuairand.py --model_name ple --task click --device cuda:1 --seed 2023
python run_kuairand.py --model_name ple --task click --device cuda:1 --seed 2024
python run_kuairand.py --model_name ple --task click --device cuda:1 --seed 2025
python run_kuairand.py --model_name ple --task click --device cuda:1 --seed 2026
python run_kuairand.py --model_name ple --task long --device cuda:1 --seed 2022
python run_kuairand.py --model_name ple --task long --device cuda:1 --seed 2023
python run_kuairand.py --model_name ple --task long --device cuda:1 --seed 2024
python run_kuairand.py --model_name ple --task long --device cuda:1 --seed 2025
python run_kuairand.py --model_name ple --task long --device cuda:1 --seed 2026
python run_kuairand.py --model_name ple --domain 0 --device cuda:1 --seed 2022
python run_kuairand.py --model_name ple --domain 0 --device cuda:1 --seed 2023
python run_kuairand.py --model_name ple --domain 0 --device cuda:1 --seed 2024
python run_kuairand.py --model_name ple --domain 0 --device cuda:1 --seed 2025
python run_kuairand.py --model_name ple --domain 0 --device cuda:1 --seed 2026
python run_kuairand.py --model_name ple --domain 1 --device cuda:1 --seed 2022
python run_kuairand.py --model_name ple --domain 1 --device cuda:1 --seed 2023
python run_kuairand.py --model_name ple --domain 1 --device cuda:1 --seed 2024
python run_kuairand.py --model_name ple --domain 1 --device cuda:1 --seed 2025
python run_kuairand.py --model_name ple --domain 1 --device cuda:1 --seed 2026
python run_kuairand.py --model_name ple --domain 2 --device cuda:1 --seed 2022
python run_kuairand.py --model_name ple --domain 2 --device cuda:1 --seed 2023
python run_kuairand.py --model_name ple --domain 2 --device cuda:1 --seed 2024
python run_kuairand.py --model_name ple --domain 2 --device cuda:1 --seed 2025
python run_kuairand.py --model_name ple --domain 2 --device cuda:1 --seed 2026
