python run_movielens_rank_multi_domain.py --model_name mmoe --task click --device cuda:1 --seed 2022
python run_movielens_rank_multi_domain.py --model_name mmoe --task click --device cuda:1 --seed 2023
python run_movielens_rank_multi_domain.py --model_name mmoe --task click --device cuda:1 --seed 2024
python run_movielens_rank_multi_domain.py --model_name mmoe --task click --device cuda:1 --seed 2025
python run_movielens_rank_multi_domain.py --model_name mmoe --task click --device cuda:1 --seed 2026
python run_movielens_rank_multi_domain.py --model_name mmoe --task like --device cuda:1 --seed 2022
python run_movielens_rank_multi_domain.py --model_name mmoe --task like --device cuda:1 --seed 2023
python run_movielens_rank_multi_domain.py --model_name mmoe --task like --device cuda:1 --seed 2024
python run_movielens_rank_multi_domain.py --model_name mmoe --task like --device cuda:1 --seed 2025
python run_movielens_rank_multi_domain.py --model_name mmoe --task like --device cuda:1 --seed 2026
python run_movielens_rank_multi_domain.py --model_name mmoe --domain 0 --device cuda:1 --seed 2022
python run_movielens_rank_multi_domain.py --model_name mmoe --domain 0 --device cuda:1 --seed 2023
python run_movielens_rank_multi_domain.py --model_name mmoe --domain 0 --device cuda:1 --seed 2024
python run_movielens_rank_multi_domain.py --model_name mmoe --domain 0 --device cuda:1 --seed 2025
python run_movielens_rank_multi_domain.py --model_name mmoe --domain 0 --device cuda:1 --seed 2026
python run_movielens_rank_multi_domain.py --model_name mmoe --domain 1 --device cuda:1 --seed 2022
python run_movielens_rank_multi_domain.py --model_name mmoe --domain 1 --device cuda:1 --seed 2023
python run_movielens_rank_multi_domain.py --model_name mmoe --domain 1 --device cuda:1 --seed 2024
python run_movielens_rank_multi_domain.py --model_name mmoe --domain 1 --device cuda:1 --seed 2025
python run_movielens_rank_multi_domain.py --model_name mmoe --domain 1 --device cuda:1 --seed 2026
python run_movielens_rank_multi_domain.py --model_name mmoe --domain 2 --device cuda:1 --seed 2022
python run_movielens_rank_multi_domain.py --model_name mmoe --domain 2 --device cuda:1 --seed 2023
python run_movielens_rank_multi_domain.py --model_name mmoe --domain 2 --device cuda:1 --seed 2024
python run_movielens_rank_multi_domain.py --model_name mmoe --domain 2 --device cuda:1 --seed 2025
python run_movielens_rank_multi_domain.py --model_name mmoe --domain 2 --device cuda:1 --seed 2026