from .adapter import *
from .useless_models import *
from .mutual_info import *
# Mlp_7_Layer,MMOE,MTMD,STAR,MTMD_Domain_Expert,MTMD_Task_Expert,MTMD_Domain_Task_Expert,MTMD_Simple_Star,MTMD_Skip,MTMD_Domain_Task_Expert_wo_shared,MTMD_Domain_Task_Expert_Gate_Shared, MTMD_Domain_Task_Expert_Individual_Gate,MTMD_Task_Expert_wo_Shared,MTMD_Domain_Expert_wo_Shared,MTMD_Domain_Task_Expert_Gate_Shared_Concat,MTMD_Skip_Lora
from .adapter_dcn import DCN_MD,DCN_MD_adp
from .adapter_wd import WideDeep_MD,WideDeep_MD_adp,MLP_adap_2_layer_1_adp
from .baseline import *